### ISSUE TITLE
License Confusion

### ISSUE THREAD

**Issue by djziegler** [Equim-chan/leb128#1]
The header in the Go files says:

// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

But the LICENSE file contains the LGPL (which is not a BSD-style license).

Digging further - you are in violation of the license for the golang "dwarf.go" file from which you draw.

Their License says (in part):

   * Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
   * Redistributions in binary form must reproduce the above
copyright notice, this list of conditions and the following disclaimer
in the documentation and/or other materials provided with the
distribution.

By not including their original license, you are in violation of these terms.

I think you can include their original license + add your LGPL and be both conformant and add the additional LGPL restictions (if you want).

- Best Regards

David

**Comment by Equim-chan** [comment]
Oops, I thought I chose BSD-3-Clause and I even put the BSD badge in the README.

I think it's fine to just change it to BSD-3-Clause?
