### ISSUE TITLE
Question: DecodeUleb128

### ISSUE THREAD

**Issue by EclesioMeloJunior** [Equim-chan/leb128#2]
Hi! I'm trying to implement/understand the LEB128 algorithm and I'm using your code as a base (thanks in advance)

I have a few questions about the `DecodeUleb128` function: on line [78](https://github.com/Equim-chan/leb128/blob/d3722dc409a82ee921034724bbdd6dfc434c8bad/leb128.go#L78) there is the operation:
```
l := uint8(len(b) & 0xff)
```

then on line [81](https://github.com/Equim-chan/leb128/blob/d3722dc409a82ee921034724bbdd6dfc434c8bad/leb128.go#L81) you verify:
```
if l > 10 {
  l = 10	
}
```
1) why not checking the `len(b) > 10` directly? 
2) What's going on exactly on line 78, is just a conversion/cast?

**Comment by Equim-chan** [comment]
I can't remember why I wrote it that way.

Basically `len(b) & 0xff` is equivalent to `len(b) % 255`, but yeah it might not be necessary.
